public class EvenFibonacci {
    /*
     * Each new term in the fibonacci sequence is generated by adding the previous two terms.
     * Consider the value of the terms in the fibonacci sequence whose values do not exceed four million.
     * Find the sum of the even valued terms.
     */


    public static void main ( String[] args) {
        int a = 1;
        int tempb = 2;
        int b = 2;
        int evenSum = 0;
        // first term in subsequent pairs in the fibonacci series

        while (b <= 4000000){

            System.out.println(a);
            System.out.println(b);

            if ( b % 2 == 0){
                evenSum = b + evenSum;
            }
            tempb = a;
            a = b;
            b = tempb + b;

        }

        System.out.println(evenSum);
        
    }
    
}
